name: Hello_file

# Controls when the workflow will run
env:
  PowerShell_file: .\Hellofile.ps1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch   
  repository_dispatch:
    types: [4334663463463]
    inputs:
      Name_one: # id of input
        description: 'Enter_name'
        required: false  
        type: string
        default: 'Genadiy'
  push: 
    branches: [ "main" , "my_experiments" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Name_one: # id of input
        description: 'Enter_name'
        required: false  
        type: string
        default: 'Pasha'
  workflow_call:
   inputs:
      Name_one: # id of input
        description: 'Enter_name'
        required: false  
        type: string
        default: 'Maksim'
      
      
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Run_Hellofile:
    if: ${{ github.event_name == 'repository_dispatch' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 
     # git clone my repositories 
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
        
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
        
      - name: Write MESSAGE
        run: echo '${{ github.repository.name }}'

      - uses: actions/checkout@v3
      
      - name: Run a PowerShell script
        shell: pwsh
        run: ${{ env.PowerShell_file }} ${{ inputs.Name_one }} 
