name: Hello_file_Web
on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
      
        run: echo ${{ env.MESSAGE }}
