name: Hello_file

# Controls when the workflow will run
env:
  Python_file: Hello.py

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch   
  push: 
    branches: [ "main" , "my_experiments" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
   inputs:
      Name_one: # id of input
        description: 'Enter name'
        required: false
        type: string
        default: Maksim
      
      
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Hello_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
   
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3
      
      
        
      - name: Run a Python script 
        run: python3 ${{ env.Python_file }} ${{ inputs.Name_one }} 
