name: Python_nambers

# Controls when the workflow will run
env:
  Python_file: simple.py

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch   
  push: 
    branches: [ "main", "my_experiments" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      Number_one: # id of input
        description: 'Who to greet'
        required: true
        type: string
        default: flo
      Number_two: # id of input
        description: 'Number two'
        required: true
        type: integer   
      
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Python_nambers:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    #env: 
     # x: 40
      #y: 55
    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell   
      - name: Run a Python script
        run:   echo "deploy_target is ${{ inputs.Number_one }}"
        
      - name: Run a Python script 
        run: python3 ${{ env.Python_file }} ${{ inputs.Number_one }} ${{ inputs.Number_two }}
