
name: start_2_repositories
  
on:
  
  push:
    branches: [ "my_exp" ]
  workflow_dispatch:

jobs:
  build:
    name: Run script 2 workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          owner: R0Pasha
          repo: hello-world-docker-action
          workflow_file_name: Script_for_workflow.py
          
      - name: Run a Python script 
        run: python3 ${{ env.workflow_file_name }}
        
      - name: Run a heppy script
        run: |
          echo "heppy"
      
